# JointStatePublisher publish
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/default/model/scorpio/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/gt/base_link"
  gz_topic_name: "/model/scorpio/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/tf"
  gz_topic_name: "/model/scorpio/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/base_imu"
  gz_topic_name: "/world/default/model/scorpio/link/base_imu/sensor/base_imu/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: "GZ_TO_ROS"

# - ros_topic_name: "/front_d435i/imu"
#   gz_topic_name: "/world/default/model/scorpio/link/front_d435i/sensor/front_imu/imu"
#   ros_type_name: "sensor_msgs/msg/Imu"
#   gz_type_name: "ignition.msgs.IMU"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/front_d435i/depth/image"
#   gz_topic_name: "/world/default/model/scorpio/link/front_d435i/sensor/front_depth/depth_image"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "ignition.msgs.Image"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/front_d435i/depth/camera_info"
#   gz_topic_name: "/world/default/model/scorpio/link/front_d435i/sensor/front_depth/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "ignition.msgs.CameraInfo"
#   direction: "GZ_TO_ROS"

# # - ros_topic_name: "/front_d435i/depth/depth_image/points"
# #   gz_topic_name: "/world/default/model/scorpio/link/front_d435i/sensor/front_depth/depth_image/points"
# #   ros_type_name: "sensor_msgs/msg/PointCloud2"
# #   gz_type_name: "ignition.msgs.PointCloudPacked"
# #   direction: "GZ_TO_ROS"

# - ros_topic_name: "/front_d435i/color/image"
#   gz_topic_name: "/world/default/model/scorpio/link/front_d435i/sensor/front_color/image"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "ignition.msgs.Image"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/front_d435i/color/camera_info"
#   gz_topic_name: "/world/default/model/scorpio/link/front_d435i/sensor/front_color/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "ignition.msgs.CameraInfo"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/front_d435i/infra1/image"
#   gz_topic_name: "/world/default/model/scorpio/link/front_infra1_frame/sensor/front_infra1/image"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "ignition.msgs.Image"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/front_d435i/infra1/camera_info"
#   gz_topic_name: "/world/default/model/scorpio/link/front_infra1_frame/sensor/front_infra1/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "ignition.msgs.CameraInfo"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/front_d435i/infra2/image"
#   gz_topic_name: "/world/default/model/scorpio/link/front_infra2_frame/sensor/front_infra2/image"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "ignition.msgs.Image"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/front_d435i/infra2/camera_info"
#   gz_topic_name: "/world/default/model/scorpio/link/front_infra2_frame/sensor/front_infra2/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "ignition.msgs.CameraInfo"
#   direction: "GZ_TO_ROS"

- ros_topic_name: "/livox/lidar"
  gz_topic_name: "/world/default/model/scorpio/link/mid360/sensor/mid360_lidar/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/livox/imu"
  gz_topic_name: "/world/default/model/scorpio/link/mid360/sensor/mid360_imu/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/ydlidar/scan"
  gz_topic_name: "/world/default/model/scorpio/link/ydlidar_g4/sensor/ydlidar_g4/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/scorpio/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: "ROS_TO_GZ"
